// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRU705pMN4mXbdxesMycIRZXZ1FFIQGDc',
    appId: '1:934564261347:web:d890901d506da55d6984d6',
    messagingSenderId: '934564261347',
    projectId: 'datingdemo-1c652',
    authDomain: 'datingdemo-1c652.firebaseapp.com',
    storageBucket: 'datingdemo-1c652.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_XijI-vpBy37vN2l0BvtymMaadtqeOk',
    appId: '1:934564261347:android:2d249a5420f1c6f76984d6',
    messagingSenderId: '934564261347',
    projectId: 'datingdemo-1c652',
    storageBucket: 'datingdemo-1c652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCriaZxDZzWTXCmLNNwxOOZRraL_g8_l4A',
    appId: '1:934564261347:ios:18455bd39a1fee8f6984d6',
    messagingSenderId: '934564261347',
    projectId: 'datingdemo-1c652',
    storageBucket: 'datingdemo-1c652.firebasestorage.app',
    androidClientId: '934564261347-ferq658lb8urdp2l3r6mihot7dcrjrjb.apps.googleusercontent.com',
    iosClientId: '934564261347-qnq39lpbjk75seoqgkmuocg85u2m9670.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingdemoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCriaZxDZzWTXCmLNNwxOOZRraL_g8_l4A',
    appId: '1:934564261347:ios:18455bd39a1fee8f6984d6',
    messagingSenderId: '934564261347',
    projectId: 'datingdemo-1c652',
    storageBucket: 'datingdemo-1c652.firebasestorage.app',
    androidClientId: '934564261347-ferq658lb8urdp2l3r6mihot7dcrjrjb.apps.googleusercontent.com',
    iosClientId: '934564261347-qnq39lpbjk75seoqgkmuocg85u2m9670.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingdemoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRU705pMN4mXbdxesMycIRZXZ1FFIQGDc',
    appId: '1:934564261347:web:ade6bddb4e41213c6984d6',
    messagingSenderId: '934564261347',
    projectId: 'datingdemo-1c652',
    authDomain: 'datingdemo-1c652.firebaseapp.com',
    storageBucket: 'datingdemo-1c652.firebasestorage.app',
  );
}
